### PR TITLE
ported to elm 0.19

### PR DESCRIPTION
**Pull request by eelcoh**

### CODE REVIEW

**Comment by eelcoh** [comment]
Main impact is in the test suite, where i had to remove the Lazy List dependency and use List Extra's iterate instead.
Other impact:

- move elm-package.json to elm.json
- remove elm-package.json in tests folder
- add test dependencies to main elm.json
- tested with elm-test@0.19.0-beta4 (to install: `npm i -g elm-test@0.19.0-beta4`)

**Comment by eelcoh** [comment]
Travis test fail. Don't have travis running myself. But it probably has to do with the new elm-test version. Elm-test succeeds locally.

**Comment by eelcoh** [comment]
Travis script depends on `elm-ops-tooling`, which has not been upgraded yet. Guess that's it for me then.

Moreover, it does not seem to export the `ELM_TEST_VERSION` environment variable for reasons unknown to me.

**Comment by wernerdegroot** [comment]
Thanks for all the hard work creating this PR!

> Guess that's it for me then.

Do you mean we can't merge? Travis seems to be running fine, although the we're running a beta version of Elm 0.19...

**Comment by eelcoh** [comment]
No, I fixed it by removing the lazy list dependency. Turned out that for the specific test case no lazy list was required. So it is good to go.

**Comment by eelcoh** [comment]
BTW, it's not a beta of elm, but a beta of elm-test.

**Comment by wernerdegroot** [comment]
Ah! I assumed `0.19.0-bugfix2` was some sort of beta too. I'll merge and publish today :thumbsup:

**Pull request merged**
