### PR TITLE
Allow for more flexible searching of a Zipper list

### PR DESCRIPTION
**Pull request by maorleger**
findFirst will search from the first element

findNext will search from the next element

### CODE REVIEW

**Comment by stoeffel** [comment]
hmmm... will have to think a bit about this after seeing it implemented.
I can also see that one would like to search backwards like `findLast` and I still think it's not really obvious where `find` is searching for an item. maybe there should be a `findInZipper`, findBefore and findAfter....
or maybe it's enough to just have a findForwards and findBackwards starting from the current position.
Thanks for your contribution ❤️
Interested to hear what others think.

**Comment by wernerdegroot** [comment]
Sorry that has taken me so long to notice this PR! I have switched jobs and am somewhat preoccupied at the moment. Nevertheless, here are my two cents.

The name `findNext` for me communicates that we start searching from the current `Zipper`, **not** including the current item. I would therefore prefer `findFromCurrent` and (likewise) `findFromStart`. 

To search backwards, wouldn't it be better to have a `reverse` method for the entire `Zipper`? That could come in handy in other places at well.

**Comment by wernerdegroot** [comment]
Ah, I see that now `findNext` indeed skips the current item. Should we then rename `find` (which clearly doesn't communicate very well) to `findFromCurrent` or something similar?

**Comment by maorleger** [comment]
Thanks for the feedback by the way! I'm happy to make any changes as per your recommendations. My thinking behind leaving find alone was to avoid breaking changes but it is confusing in my opinion until you are familiar with how zipper lists work.

Thank you for considering my PR!

**Comment by wernerdegroot** [comment]
Thank YOU for contributing to the library! 

What do you think is the best name for the current `find`?

**Comment by maorleger** [comment]
Short answer: `findFromCurrent` is a fine name

Long answer: 

I think if you wanted to rename `find` then `findFromCurrent` is a fine name; however, and I realize hindsight is always 20-20, if it were my library I'd keep find as is as a helper method but no longer expose it as part of the public interface of the module.

I think of finding something in a zipper list as jumping to a page. `findNext` and `findFirst` cover most use cases. `findFromCurrent` will cover the one remaining case where the item you'd want to find IS the current item in the zipper in which case it is the equivalent of jumping from the current page to the current page - it's superfluous given `current` 

Happy to submit another PR by the way if you wanted to go in a certain direction or even amend this PR - but that's my 2 cents. Hope that makes sense!

**Pull request merged**
