### PR TITLE
Upgrade main module and tests to elm 0.18

### PR DESCRIPTION
**Pull request by wehlutyk**
It was straight-forward:
* Update library and test dependencies
* Update library and test elm versions
* Update test boilerplate
* Bump package version

I use this in my project, so will be very grateful if it gets published on Elm Packages!

Cheers

### CODE REVIEW

**Comment by wehlutyk** [comment]
I just realized there's been some API changes between 2.0.0 and the current master branch, so the version bump I made is wrong. Reverting back.

**Comment by wernerdegroot** [comment]
Thanks for the contribution! I'll publish a 3.0.0 later tonight!

**Comment by wernerdegroot** [comment]
If you prefer, we could also publish the upgrade first, and "break the API" in another version. This way, you don't have to spend a lot of time in your transition to 0.18 (and deal with changes in the API another time). What do you say, @wehlutyk

**Comment by wehlutyk** [comment]
I can wait no problem, don't bother publishing twice! Thanks though :)

**Comment by wehlutyk** [comment]
Awesome (and published!), thanks!

**Pull request merged**
